(defun fix (node)
  (declare (type node node))
  (when (red? (node-right node))
    (rotlf node))
  (when (and (red? (node-left node)) (red? (node-left (node-left node))))
    (rotrf node))
  (when (and (red? (node-left node)) (red? (node-right node)))
    (flip node))
  node)