(defun v+w*c (v w c)
  (assert (= (length v) (length w)))
  (let* ((n (length v))
	 (res (make-vector n)))
    (dotimes (i n)
      (setf (aref res i)
	    (+ (aref v i)
	       (* c (aref w i)))))
    res))