(defun polyline (&rest pts)
  (begin-path)
  (do ((i 0 (+ i 2)))
      ((>= i (length pts)))
    (let ((x (aref pts i))
          (y (aref pts (1+ i))))
      (if (= i 0)
          (move-to x y)
          (line-to x y)))))