(defun print-td-rest (td endsym str)
  (cond ((null td) (princ endsym str))
	((atom td)
	 (princ ". " str)
	 (prin1 td str) (princ endsym str))
	((null (cdr td))
	 (prin1 (car td) str)
	 (princ endsym str))
	(t (prin1 (car td) str)
	 (princ " " str)
	 (print-td-rest (cdr td) endsym str))))
