(defun bracket (x)
  (cond ((atom x)
	 (list *bq-list* (bq-process x)))
	((eq (car x) *comma*)
	 (list *bq-list* (cadr x)))
	((eq (car x) *comma-atsign*)
	 (cadr x))
	((eq (car x) *comma-dot*)
	 (list *bq-clobberable* (cadr x)))
	(t (list *bq-list* (bq-process x)))))