(defun p5-quad (&key x1 y1 x2 y2 x3 y3 x4 y4)
  (fly-to :x x1 :y y1)
  (with-tool-down (*p5-depth*)
		(format t "p5 depth: ~A~%" (current-z))
    (mill-abs :x x2 :y y2)
    (mill-abs :x x3 :y y3)
    (mill-abs :x x4 :y y4)
    (mill-abs :x x1 :y y1))
  )