  (defstate scheme-lexer :multiline-comment ()
    ("#\\|" :comment.multiline (state :multiline-comment))
    ("\\|#" :comment.multiline (state :pop!))
    ("[^|#]+" :comment.multiline)
    ("[|#]" :comment.multiline))